---
- name: Enable UFW
  community.general.ufw:
    state: enabled
  when: firewall_enabled | bool
  become: true

- name: Ensure UFW is started and enabled at boot
  ansible.builtin.service:
    name: ufw
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled_at_boot }}"
  become: true

- name: Allow specified ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ firewall_allowed_ports }}"
  become: true
  tags: ufw_policy

- name: Set UFW default incoming policy
  community.general.ufw:
    rule: "{{ firewall_default_incoming_policy }}"
    direction: in
  become: true
  tags: ufw_policy

- name: Set UFW default outgoing policy
  community.general.ufw:
    rule: "{{ firewall_default_outgoing_policy }}"
    direction: out
  become: true
  tags: ufw_policy
