---
- name: Create Promtail directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_management_promtail_user_name }}"
    group: "{{ user_management_promtail_group }}"
    mode: '0755'
  loop:
    - "{{ log_management_promtail_install_dir }}"
    - "{{ log_management_promtail_config_dir }}"
    - "{{ log_management_promtail_positions_file_path }}"
  become: true
  when: log_management_enable_promtail

# resorted to command module since get_url had issues with certificates
# CustomHTTPSConnection object has no attribute 'cert_file'
- name: Download Latest Promtail from the official GitHub Repository
  ansible.builtin.command:
    cmd: >
      nohup curl -L -o /tmp/promtail-linux-amd64.zip {{ log_management_promtail_binary_url }}
  register: download_result
  retries: 3
  delay: 5
  until: download_result.rc == 0
  changed_when: download_result.rc == 0
  become: true
  when: log_management_enable_promtail
  tags: download_promtail

- name: Unarchive Promtail binary
  ansible.builtin.unarchive:
    src: /tmp/promtail-linux-amd64.zip
    dest: "{{ log_management_promtail_install_dir }}"
    remote_src: true
  become: true
  when: log_management_enable_promtail
  tags: download_promtail

- name: Check if promtail-linux-amd64 exists
  ansible.builtin.stat:
    path: "{{ log_management_promtail_install_dir }}/promtail-linux-amd64"
  register: promtail_linux_amd64
  when: log_management_enable_promtail
  tags: download_promtail

- name: Rename Promtail binary
  ansible.builtin.command:
    cmd: mv "{{ log_management_promtail_install_dir }}/promtail-linux-amd64" "{{ log_management_promtail_install_dir }}/promtail"
  become: true
  when:
    - log_management_enable_promtail
    - promtail_linux_amd64.stat.exists
  changed_when: download_result.rc == 0
  tags: download_promtail

- name: Create Promtail configuration
  ansible.builtin.template:
    src: promtail-config.yml.j2
    dest: "{{ log_management_promtail_config_file }}"
    owner: "{{ user_management_promtail_user_name }}"
    group: "{{ user_management_promtail_group }}"
    mode: '0644'
  become: true
  when: log_management_enable_promtail
  notify: Restart Promtail

- name: Create Promtail systemd service
  ansible.builtin.template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: '0644'
  become: true
  when: log_management_enable_promtail
  notify: Restart Promtail
  tags: promtail_service

- name: Ensure Promtail service is enabled and started
  ansible.builtin.systemd:
    name: promtail
    enabled: true
    state: started
  become: true
  when: log_management_enable_promtail
  tags: promtail_service
